const list = [
    { 
      id: 0,
      title: "Pijamas",
      img: "/images/pijama-3.jpg",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
      descripcion: "Esta es una descripcion",
    },
    {
      id: 1,
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
      descripcion: "Esta es una descripcion",
    },
    { 
      id: 2,
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
      descripcion: "Esta es una descripcion",
    },
    {
      id: 3,
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
      descripcion: "Esta es una descripcion",
    },
    {
      id: 4,
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
      descripcion: "Esta es una descripcion",
    },
    {
      id: 5,
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
      descripcion: "Esta es una descripcion",
    },
    {
      id: 6,
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
      descripcion: "Esta es una descripcion",
    },
    {
      id: 7,
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
      descripcion: "Esta es una descripcion",
    },
    {
      id: 8,
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
      descripcion: "Esta es una descripcion",
    },
    {
      id: 9,
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
      descripcion: "Esta es una descripcion",
    },
    {
      id: 10,
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
      descripcion: "Esta es una descripcion",
    },
    {
      id: 11,
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
      descripcion: "Esta es una descripcion",
    }
  ];

  export default list