const list = [
    {
      title: "Pijamas",
      img: "/images/pijama-3.jpg",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
    },
    {
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
    },
    {
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
    },
    {
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
    },
    {
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
    },
    {
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
    },
    {
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
    },
    {
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
    },
    {
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
    },
    {
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
    },
    {
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
    },
    {
      title: "Pijamas",
      img: "/images/pijama-2.png",
      cantidad: "4 modelos",
      price: "COP 45.000",
      category: "Bralet",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/images/pijama-1.jpeg",
        modelo2: "/images/pijama-2.png",
        modelo3: "/images/pijama-3.jpg",
      },
    }
  ];

  export default list