const list = [
    {
      title: "Lenceria",
      img: "/images/lenceria1.jpg",
      cantidad: "3 modelos",
      price: "COP 35.000",
      category: "Bralet",
      tipo: "Lenceria",
      productMedia: {
        modelo1: "/images/lenceria1.jpg",
        modelo2: "/images/lenceria2.webp",
        modelo3: "/images/lenceria3.jpg",
      },
    },
    {
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
      }, {
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
      }, {
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
      }, {
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
      }, {
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
      }, {
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
      }, {
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
      }, {
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
      }, {
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
      }, {
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
      }, {
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
      }
  ];

  export default list