const list = [
    {
      id: 0,
      title: "Lenceria",
      img: "/images/lenceria1.jpg",
      cantidad: "3 modelos",
      price: "COP 35.000",
      category: "Bralet",
      tipo: "Lenceria",
      productMedia: {
        modelo1: "/images/lenceria1.jpg",
        modelo2: "/images/lenceria2.webp",
        modelo3: "/images/lenceria3.jpg",
      },
      descripcion: "Esta es una descripcion",
    },
    {   
        id: 1,
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
        descripcion: "Esta es una descripcion",
      }, {
        id: 2,
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
        descripcion: "Esta es una descripcion",
      }, {
        id: 3,
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
        descripcion: "Esta es una descripcion",
      }, {
        id: 4,
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
        descripcion: "Esta es una descripcion",
      }, {
        id: 5,
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
        descripcion: "Esta es una descripcion",
      }, {
        id: 6,
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
        descripcion: "Esta es una descripcion",
      }, {
        id: 7,
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
        descripcion: "Esta es una descripcion",
      }, {
        id: 8,
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
        descripcion: "Esta es una descripcion",
      }, {
        id: 9,
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
        descripcion: "Esta es una descripcion",
      }, {
        id: 10,
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
        descripcion: "Esta es una descripcion",
      }, {
        id: 11,
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
        descripcion: "Esta es una descripcion",
      }
  ];

  export default list