const list = [
    { 
      id: 0,
      title: "BATA CON TIRAS",
      img: "/imagenes/BATA1.jpg",
      cantidad: "4 modelos",
      price: "COP 35.000",
      category: "Satin",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/imagenes/BATA2.jpg",
        modelo2: "/imagenes/BATA3.jpg",
        modelo3: "/imagenes/BATA4.jpg",
      },
      descripcion: "Disfruta de la comodidad y el lujo con nuestra pijama elaborada en satín licrado. Este material suave y elástico te brinda una sensación de frescura y confort, ideal para tus noches de descanso.",
      descripcion2: "Puedes elegir entre nuestras telas disponibles en el momento para fabricar una pijama con tu talla específica. Así, tendrás una prenda única y hecha a medida, incluso si no aparece en nuestras fotos.",
    },
    {
      id: 1,
      title: "SHORT Y CROP TOP",
      img: "/imagenes/CROP1.jpg",
      cantidad: "4 modelos",
      price: "COP 35.000",
      category: "Satin y Encaje",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/imagenes/CROP2.jpg",
        modelo2: "/imagenes/CROP3.jpg",
        modelo3: "/imagenes/CROP4.jpg",
      },
      descripcion: "Disfruta de la sofisticación y el confort con nuestro conjunto de crop top y short. El crop top está hecho en encaje elástico, proporcionando un ajuste delicado y elegante que realza tu figura. El short está confeccionado en satín, con encaje en los orillos, brindándote una sensación de lujo y suavidad.",
      descripcion2: "Puedes elegir entre nuestras telas disponibles en el momento para fabricar una pijama con tu talla específica. Así, tendrás una prenda única y hecha a medida, incluso si no aparece en nuestras fotos.",
    },
    {
        id: 2,
        title: "SHORT Y CROP TOP",
        img: "/imagenes/CROP5.jpg",
        cantidad: "4 modelos",
        price: "COP 35.000",
        category: "Satin y Encaje",
        tipo: "Pijama",
        productMedia: {
          modelo1: "/imagenes/CROP6.jpg",
          modelo2: "/imagenes/CROP7.jpg",
          modelo3: "/imagenes/CROP4.jpg",
        },
        descripcion: "Disfruta de la sofisticación y el confort con nuestro conjunto de crop top y short. El crop top está hecho en encaje elástico, proporcionando un ajuste delicado y elegante que realza tu figura. El short está confeccionado en satín, con encaje en los orillos, brindándote una sensación de lujo y suavidad.",
        descripcion2: "Puedes elegir entre nuestras telas disponibles en el momento para fabricar una pijama con tu talla específica. Así, tendrás una prenda única y hecha a medida, incluso si no aparece en nuestras fotos.",
      },
    { 
      id: 3,
      title: "CUELLO Y BOTONES",
      img: "/imagenes/BOTONES1.jpg",
      cantidad: "4 modelos",
      price: "COP 65.000",
      category: "Satin",
      tipo: "Pijama",
      productMedia: {
        modelo1: "/imagenes/BOTONES2.jpg",
        modelo2: "/imagenes/BOTONES3.jpg",
        modelo3: "/imagenes/BOTONES4.jpg",
      },
      descripcion: "Disfruta de la comodidad y el lujo con nuestra pijama elaborada en satín licrado. Este material suave y elástico te brinda una sensación de frescura y confort, ideal para tus noches de descanso.",
      descripcion2: "Puedes elegir entre nuestras telas disponibles en el momento para fabricar una pijama con tu talla específica. Así, tendrás una prenda única y hecha a medida, incluso si no aparece en nuestras fotos.",
    },
    { 
        id: 4,
        title: "CUELLO Y BOTONES",
        img: "/imagenes/BOTONES5.jpg",
        cantidad: "4 modelos",
        price: "COP 65.000",
        category: "Satin",
        tipo: "Pijama",
        productMedia: {
          modelo1: "/imagenes/BOTONES6.jpg",
          modelo2: "/imagenes/BOTONES7.jpg",
          modelo3: "/imagenes/BOTONES8.jpg",
        },
        descripcion: "Disfruta de la comodidad y el lujo con nuestra pijama elaborada en satín licrado. Este material suave y elástico te brinda una sensación de frescura y confort, ideal para tus noches de descanso.",
        descripcion2: "Puedes elegir entre nuestras telas disponibles en el momento para fabricar una pijama con tu talla específica. Así, tendrás una prenda única y hecha a medida, incluso si no aparece en nuestras fotos.",
      },
    {
      id: 5,
      title: "TIRAS Y SHORT",
      img: "/imagenes/TIRAS1.jpg",
      cantidad: "",
      price: "COP 35.000",
      category: "Satin",
      tipo: "Pijama",
      productMedia: {
        modelo1: "",
        modelo2: "",
        modelo3: "",
      },
      descripcion: "Disfruta de la sofisticación y el confort con nuestro conjunto de camisa de tiras y short. La camisa de tiras está diseñada para ofrecerte una sensación ligera y fresca, perfecta para tus noches de descanso. Puedes elegir entre short largo o corto, ambos elaborados en satín licrado, brindándote una sensación de lujo y suavidad.",
      descripcion2: "Puedes elegir entre nuestras telas disponibles en el momento para fabricar una pijama con tu talla específica. Así, tendrás una prenda única y hecha a medida, incluso si no aparece en nuestras fotos.",
    },
    {
        id: 6,
        title: "Lenceria",
        img: "/images/lenceria1.jpg",
        cantidad: "3 modelos",
        price: "COP 35.000",
        category: "Bralet",
        tipo: "Lenceria",
        productMedia: {
          modelo1: "/images/lenceria1.jpg",
          modelo2: "/images/lenceria2.webp",
          modelo3: "/images/lenceria3.jpg",
        },
        descripcion: "Esta es una descripcion",
      },
      {   
          id: 7,
          title: "Lenceria",
          img: "/images/lenceria1.jpg",
          cantidad: "3 modelos",
          price: "COP 35.000",
          category: "Bralet",
          tipo: "Lenceria",
          productMedia: {
            modelo1: "/images/lenceria1.jpg",
            modelo2: "/images/lenceria2.webp",
            modelo3: "/images/lenceria3.jpg",
          },
          descripcion: "Esta es una descripcion",
        }, {
          id: 8,
          title: "Lenceria",
          img: "/images/lenceria1.jpg",
          cantidad: "3 modelos",
          price: "COP 35.000",
          category: "Bralet",
          tipo: "Lenceria",
          productMedia: {
            modelo1: "/images/lenceria1.jpg",
            modelo2: "/images/lenceria2.webp",
            modelo3: "/images/lenceria3.jpg",
          },
          descripcion: "Esta es una descripcion",
        }, {
          id: 9,
          title: "Lenceria",
          img: "/images/lenceria1.jpg",
          cantidad: "3 modelos",
          price: "COP 35.000",
          category: "Bralet",
          tipo: "Lenceria",
          productMedia: {
            modelo1: "/images/lenceria1.jpg",
            modelo2: "/images/lenceria2.webp",
            modelo3: "/images/lenceria3.jpg",
          },
          descripcion: "Esta es una descripcion",
        }, 
   
  ];

  export default list