import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/nav/Navbar";
import Pie from "./components/footer/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AGP Lady Lingerie",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Pie />
        </body>
       
    </html>
  );
}
